spring:
  application:
    name: sistema-login

  datasource:
    url: jdbc:postgresql://localhost:5432/sistema-login
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: projetologinbd@gmail.com
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

