spring:
  application:
    name: sistema-login

  datasource:
    url: jdbc:postgresql://localhost:5432/sistema-login
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect